version: "3.8"

services:
  relay:
    build:
      context: .
      dockerfile: Dockerfile.relay
    container_name: walkie-songie-relay
    restart: unless-stopped
    environment:
      - SECRET_KEY_SEED=42
      - TCP_PORT=9000
      - WS_PORT=9001
    expose:
      - "9001"
    labels:
      # Traefik v2 labels
      - "traefik.enable=true"

      # WebSocket router (main browser connection)
      - "traefik.http.routers.libp2p-relay.rule=Host(`libp2p.wondering.xyz`)"
      - "traefik.http.routers.libp2p-relay.entrypoints=websecure"
      - "traefik.http.routers.libp2p-relay.tls=true"
      - "traefik.http.routers.libp2p-relay.tls.certresolver=letsencrypt"

      # Service configuration
      - "traefik.http.services.libp2p-relay.loadbalancer.server.port=9001"
    networks:
      - traefik

networks:
  traefik:
    external: true
